---
apiVersion: v1
kind: Service
metadata:
  name: fedora-vm-rs
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    kubevirt.io/domain: fedora-vm-rs
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fedora-vm-rs
  annotations:
    kubernetes.io/ingress.class: "openshift-default"
    route.openshift.io/termination: "edge"
    route.openshift.io/insecureEdgeTerminationPolicy: "Redirect"
spec:
  ingressClassName: openshift-default
  rules:
    - host: kcd-rs.apps.lab.clusters.t-k.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: fedora-vm-rs
                port: 
                  number: 8080
